# Generated by Django 4.1.7 on 2023-03-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0003_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentTest',
        ),
    ]
